#define BUILD_TIME "Thu Aug 16 04:16:40 PDT 2018"
#define CC "mpicc (gcc)"
#define CC_FORTRAN_INT int
#define CFLAGS "-g -O2"
#define F90_ACCEPTS_LINE_NUMBERS 1
#define FC "mpif90 (gfortran)"
#define FCFLAGS "-ffree-line-length-none"
#define FC_COMMAND_LINE_ARGUMENTS 2003
#define FC_FUNC(name,NAME) name ## _
#define FC_FUNC_(name,NAME) name ## _
#define FC_INTEGER_SIZE 4
#define GIT_COMMIT ""
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALPHASORT 1
#define HAVE_ARPACK 1
#define HAVE_BLACS 1
#define HAVE_BLAS 1
#define HAVE_BUILTIN_PREFETCH 1
#define HAVE_CLOSEDIR 1
#define HAVE_COMP_ISF 1
#define HAVE_COMP_METIS 1
#define HAVE_DIRENT_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FC_COMPILER_VERSION 1
#define HAVE_FC_SIZEOF 1
#define HAVE_FFTW3 1
#define HAVE_FFTW3_MPI 1
#define HAVE_FFTW3_THREADS 1
#define HAVE_FLUSH 1
#define HAVE_FORTRAN_LOC 1
#define HAVE_GETOPT_LONG 1
#define HAVE_GETPID 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_INTTYPES_H 1
#define HAVE_IOCTL 1
#define HAVE_LAPACK 1
#define HAVE_LIBXC 1
#define HAVE_LIBXC_HYB_MGGA 1
#define HAVE_M128D 1
#define HAVE_MEMORY_H 1
#define HAVE_METIS 1
#define HAVE_MPI 1
#define HAVE_MPI2 1
#define HAVE_NANOSLEEP 1
#define HAVE_PERROR 1
#define HAVE_READDIR 1
#define HAVE_SBRK 1
#define HAVE_SCALAPACK 1
#define HAVE_SCANDIR 1
#define HAVE_SIGACTION 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCASESTR 1
#define HAVE_STRCHR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRNDUP 1
#define HAVE_STRSIGNAL 1
#define HAVE_STRTOD 1
#define HAVE_SYSCONF 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TCGETPGRP 1
#define HAVE_UINT32_T 1
#define HAVE_UINT64_T 1
#define HAVE_UNAME 1
#define HAVE_UNISTD_H 1
#define HAVE_VEC 1
#define HAVE_YAML /**/
#define ISO_C_BINDING 1
#define LONG_LINES 1
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define MAX_DIM 3
#define MPI_H 1
#define OCT_ARCH x86_64
#define PACKAGE "octopus"
#define PACKAGE_BUGREPORT "octopus-devel@tddft.org"
#define PACKAGE_NAME "Octopus"
#define PACKAGE_STRING "Octopus 8.2"
#define PACKAGE_TARNAME "octopus"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "8.2"
#define SIZEOF_SIZE_T 8
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_VOIDP 8
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define TLS_SPECIFIER __thread
#define VERSION "8.2"
#define YAML_VERSION_MAJOR 0
#define YAML_VERSION_MINOR 1
#define YAML_VERSION_PATCH 4
#define YAML_VERSION_STRING "0.1.4"
#define restrict __restrict
